const express=require("express"),fs=require("fs");const{port,catalogFile,refreshHours,tmdbToken}=require("./config"),{main:refresh}=require("./refresh");const app=express();app.disable("x-powered-by");
const CATALOG_ID="greece-theatrical-12m-v2";
const manifest={id:"gr.cinema.rolling12m.v2",version:"2.1.0",name:"Ελλάδα • Κινηματογραφικές Κυκλοφορίες 12μήνου",description:"Δυναμικός κατάλογος ταινιών με επαληθευμένη κινηματογραφική κυκλοφορία στην Ελλάδα μέσα στο κυλιόμενο τελευταίο 12μηνο. Ταξινόμηση αποκλειστικά με ελληνική κινηματογραφική ημερομηνία, νεότερες πρώτες.",resources:["catalog"],types:["movie"],catalogs:[{type:"movie",id:CATALOG_ID,name:"🇬🇷 Ελλάδα • 12μηνο (GR date)",extra:[{name:"skip",isRequired:false}]}],idPrefixes:["tt"]};
function readCatalog(){try{return JSON.parse(fs.readFileSync(catalogFile,"utf8"))}catch{return{generatedAt:null,count:0,items:[]}}}
function sortedItems(){return [...(readCatalog().items||[])].sort((a,b)=>String(b.greekTheatricalDate||"").localeCompare(String(a.greekTheatricalDate||""))||String(a.name||"").localeCompare(String(b.name||""),"el"));}
function metas(skip=0){return sortedItems().slice(skip,skip+100).map(x=>({id:x.id,type:"movie",name:x.name,poster:x.poster||`https://images.metahub.space/poster/medium/${x.id}/img`,releaseInfo:x.greekTheatricalDate,description:`Ελληνική κινηματογραφική κυκλοφορία: ${x.greekTheatricalDate}`}))}
function fresh(res){res.set("Cache-Control","no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0");res.set("Surrogate-Control","no-store");res.set("Pragma","no-cache");res.set("Expires","0");return res}
app.get("/manifest.json",(_,res)=>fresh(res).json(manifest));
app.get(`/catalog/movie/${CATALOG_ID}.json`,(_,res)=>fresh(res).json({metas:metas(0)}));
app.get(`/catalog/movie/${CATALOG_ID}/:extra.json`,(req,res)=>{const m=String(req.params.extra||"").match(/(?:^|&)skip=(\d+)/);fresh(res).json({metas:metas(m?Number(m[1]):0)})});
app.get("/health",(_,res)=>{const c=readCatalog();const s=sortedItems();fresh(res).json({ok:true,version:manifest.version,catalogId:CATALOG_ID,generatedAt:c.generatedAt,count:c.count,window:c.window,first10:s.slice(0,10).map(x=>({id:x.id,name:x.name,greekTheatricalDate:x.greekTheatricalDate})),odyssey:s.find(x=>x.id==="tt33764258")||null})});
app.get("/",(_,res)=>res.type("html").send(`<!doctype html><meta charset="utf-8"><title>${manifest.name}</title><h1>${manifest.name}</h1><p>${manifest.description}</p><p>Manifest: <code>/manifest.json</code></p>`));
let refreshing=false;async function safeRefresh(){if(refreshing||!tmdbToken)return;refreshing=true;try{await refresh()}catch(e){console.error("Refresh failed:",e)}finally{refreshing=false}}app.listen(port,()=>{console.log(`Listening on ${port}`);safeRefresh();setInterval(safeRefresh,Math.max(1,refreshHours)*3600_000).unref()});
